name: todo
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  intl: ^0.19.0
  equatable: ^2.0.5
  connectivity_plus: ^6.0.5
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  msh_checkbox: ^2.0.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_animations: ^1.1.1
  path_provider: ^2.0.8
  mockito: ^5.4.4
  workmanager: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/